### ISSUE TITLE
Why not to use java esl library?

### ISSUE THREAD

**Issue by arthur-s** [CallHandling/freeswitch-scala-esl#1]
Why not to use java esl library? I'm thinking wheather to learn scala language, and reading about this language, and as I understood, scala can use Java libraries...

**Comment by nathanleyton** [comment]
You can easily use the Java ESL from Scala. We are making a functional / reactive ESL using akka streams, at the same time using Scala as core language.

**Comment by arthur-s** [comment]
what you want to do - will this lib support outbound and inbound modes? Also one question - approximitely when will you deploy your lib, so we can use it? If I begin learn scala now, will I be ready to use this lib in production :) ? (I never learned functional programming languages, but choosing between erlang, elixir, clojure and scala)

**Comment by nathanleyton** [comment]
I am not able to give you a lead time at the moment, we have only just started planning, however once we start we would be happy to include you as a contributor if you wish. Yes, planning to support both modes. Welcome to the world of functional programming :)

**Comment by geekbytes-io** [comment]
@arthur-s 
we have published v1.01
https://search.maven.org/#artifactdetails%7Cuk.co.callhandling%7Cfreeswitch-scala-esl_2.12%7C1.01%7Cjar
